### ISSUE TITLE
small int overflow on non-longint board

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_DS3231#30]
Discord user thesmelliestone could not use this library on a Trinket M0. It appears that a register read is assuming longint support:

```python
import adafruit_ds3231
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ds3231.py", line 67, in <module>
  File "adafruit_ds3231.py", line 97, in DS3231
  File "adafruit_register/i2c_bits.py", line 63, in init
OverflowError: small int overflow
```

**Comment by m313** [comment]
I could replicate the error on a Gemma M0 board.

**Comment by Julien-768** [comment]
I have the same issue on feather M0 adalogger.
